### ISSUE TITLE
How to run GenPat on my own data?

### ISSUE THREAD

**Issue by XBWer** [xgdsmileboy/GenPat#78]
Hi @xgdsmileboy @FancyCoder0 , I understand the tool is mainly built on the top of the D4J data.
My question is, **how can I run it on my own buggy and fixed code pair to get the inferred transformation pattern and apply it on my own file**? Is there any easy way to do that without too many code changes? I am looking forward to hearing suggestions from you. Thx!

**Comment by xgdsmileboy** [comment]
@XBWer , thanks for your interest in GenPat. 

We have provided a set of test cases in the project. Please find the [demo case](https://github.com/xgdsmileboy/GenPat/blob/master/src/test/java/mfix/core/node/match/MatcherTest.java#L388) for your reference. However, please note this test case has a fiter at [line 403](https://github.com/xgdsmileboy/GenPat/blob/master/src/test/java/mfix/core/node/match/MatcherTest.java#L403), which targets to the "replace" method. You can change the code on demand.

I think it would be easy for you. Enjoy!

**Comment by XBWer** [comment]
Awesome! I appreciate your prompt reply and help. I will check it out.
